include:
  - ./infra/mongodb/docker-compose.mongo.yaml

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    restart: always
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - mongos1